### ISSUE TITLE
Moving observable.js from RIot

### ISSUE THREAD

**Issue by cognitom** [riot/observable#1]
I'm trying to extract `observable.js` to the new repo with its git history.
https://github.com/cognitom/observable/blame/dev/observable.js

But the history before [the commit](https://github.com/riot/riot/commit/06022b12c544556adf163c5fb48cd4b3b345792a) has disappeared. Original one is this.
https://github.com/riot/riot/blame/master/lib/browser/observable.js

What I've tried are these commands:

``` bash
$ git clone riotjs observable
$ cd observable/
$ git filter-branch --subdirectory-filter lib/browser/ HEAD
$ git filter-branch --index-filter 'git rm router.js' HEAD
# and remove others, too
$ git tag -d `git tag | grep -E '.'`
```

I'm new about `filter-branch`. Is there any idea?

**Comment by GianlucaGuarini** [comment]
I will be on this once riot 2.2.0 will be released. I would not overcomplicate the workflow. We can just move the observable code in here and make a npm module `riot-observable`. You should pay attention that this module should be written with an UMD export

**Comment by cognitom** [comment]
Sure.
UMD and mabe smash, too.

**Comment by GianlucaGuarini** [comment]
Probably the next release will use something like babeljs and a better build (webpack). We need to discuss about it. Now I am focused just on the next release

**Comment by cognitom** [comment]
OK, pls focus on the next release :v:

**Comment by tipiirai** [comment]
Definitely curious about babeljs and the benefits for Riot.

**Comment by GianlucaGuarini** [comment]
This repo is ready to be published on npm I am just waiting that the `riot-observable` domain on npm will be available again https://github.com/callumlocke/riot-observable/issues/1

**Comment by cognitom** [comment]
Cool!
Thanks @GianlucaGuarini

**Comment by GianlucaGuarini** [comment]
`riot-observable` is finally on npm https://www.npmjs.com/package/riot-observable

**Comment by cognitom** [comment]
:tada:

**Comment by GianlucaGuarini** [comment]
the current riot in the `dev` branch loads this submodule without any problem. Closing this issue
