### ISSUE TITLE
Documentation for standalone usage for base libraries that compose into riot

### ISSUE THREAD

**Issue by btakita** [riot/observable#12]
Is this possible?

`libraryA` depends on `riot-observable`
`libraryB` depends on `libraryA` & `riot`

Can `riot-observable` from `libraryA` be part of the `libraryB` build?
Is this possible using `commonjs` via `browserify`?

**Comment by btakita** [comment]
It does not seem like `riot/observable` is compatible with `commonjs`. Here's what I came up with.

``` javascript
var observable = (typeof riot === 'undefined' ? require('riot') : riot).observable;
```

**Comment by GianlucaGuarini** [comment]
@btakita You are right I will make a new release providing an `UMD` output

**Comment by GianlucaGuarini** [comment]
I am working on a version that could be bundled using `rollup` and eventually `commonjs` https://github.com/riot/riot/tree/rollup please hold on because it's quite a big change

**Comment by GianlucaGuarini** [comment]
this library is completely standalone i am closing this issue
