### ISSUE TITLE
Can we have the given methods as configurable: true?

### ISSUE THREAD

**Issue by wintercounter** [riot/observable#13]
I had a case where should had to wrap `.on`, because I had to do some preprocessing on the event name. Now I've did a workaround, but it's really ugly :)

**Comment by yuretz** [comment]
This would also be useful if #3 is not going to be fixed, because then we would be able to override `.on` and wrap event handlers in try..catch  to provide our own default error handling behavior, if needed.

**Comment by GianlucaGuarini** [comment]
the issue #3 was solved and the `busy` flag was removed in the v3.0.0 currently in alpha.

**Comment by GianlucaGuarini** [comment]
I am closing this issue because I think that patching the observable methods is never a good idea.
