### ISSUE TITLE
Stop event "propagation"

### ISSUE THREAD

**Issue by wellguimaraes** [riot/observable#16]
I was wondering if observable.trigger could return false if it was interrupted before executing completely all registered handlers. Any event handler could return false to interrupt the triggering sequence, just like when we want to break an array.forEach iteration.

Some use cases:
- prevent tag update (riot 3 milestone), just returning false on an 'update' handler, instead of setting an attribute or something else;
- prevent tag unmount, returning false on a 'before-unmount' handler, so we could apply animations before unmounting tags;

What do you think of it?

**Comment by GianlucaGuarini** [comment]
Riot.js 3 and 4 have the `shouldUpdate` callback. Please use it to prevent your components updates
