### ISSUE TITLE
how can i execute the branch as `if (fns[i] !== fn) { i-- }` 

### ISSUE THREAD

**Issue by chenjunxyf** [riot/observable#25]
the  code of  `trigger`, i can't understand 

``` javascript
if (fns[i] !== fn) { i-- }
```

can you show me  how can i execute this branch? thanks~

**Comment by GianlucaGuarini** [comment]
It allows you to trigger recursive events without being stuck http://plnkr.co/edit/RKHV8Y8aYg5tl3zqjGXK?p=preview

Please note that recursive events will not be supported in riot@3.0.0 to solve https://github.com/riot/observable/issues/3

**Comment by chenjunxyf** [comment]
thank you very much
