### ISSUE TITLE
Can observable return a disposable when subscribe an event?

### ISSUE THREAD

**Issue by hank4work** [riot/observable#26]
First of all, thanks for you guys' work. It's awesome!

In my SPA, there is an observable object, named XBUS. I use XBUS to be the message hub. XBUS is a global object. And all other objects in the app can publish EVENT via call `XBUS.trigger('EVENT', p)`. Of course, they can subscribe EVENT via call `XBUS.on('EVENT', fn)`.

I have a tag, named TagA. There are ten instances of TagA, and all these instances listening on the same EVENT via XBUS. 
```
XBUS.on('EVENT-NAME', () => { 
  //do something 
})
```

The question is: if I wanna stop one instance's listening (just stop, do NOT unmount the instance), how can I make it?

Can observable return a disposable when subscribe an event? If so,  I can turn off the subscription explicit.

**Comment by GianlucaGuarini** [comment]
> Can observable return a disposable when subscribe an event? If so, I can turn off the subscription explicit.

No you need to rely on the `off` method:

```js
function doSomething(val) {
  if (condition) this.off(doSomething)
}
XBUS.on('EVENT-NAME', doSomething)
```
