### ISSUE TITLE
Hooks for debugging

### ISSUE THREAD

**Issue by damusix** [riot/observable#28]
Looking to make a debugger to help follow event trail. Currently, I am doing this:

``` javascript
const observable = riot.observable;

const debugFn = function (obj, fn, action, args) {

  if (app.debugger && app.debugger.on) {

    app.debugger.trigger('state', obj, fn, action, args);
  }
}

export function debuggableObserver (obj) {

  obj = obj || {};

  if (obj.ELEMENT_NODE) {

    obj.__name = obj.id || obj.getAttribute('name') || obj.localName;
    console.log(obj.__name);
  }

  const self = this;

  // Observerable observer for this instance
  const observer = observable();

  // Properties object to rewrap
  const properties = {};

  // Rewrap observer functions for debugging
  ['on', 'one', 'off', 'trigger'].forEach((fn) => {

    // Rewrap and log if debugging
    const execFn = function () {


      const args = Array.prototype.slice.apply(arguments);
      const action = args.shift();

      debugFn.apply({}, [obj, fn, action, args]);

      observer[fn].apply(observer[fn], arguments);
    };

    // Make sure those functions cannot be overwritten
    properties[fn] = {
      value: execFn,
      enumerable: false,
      writable: false,
      configurable: false
    };
  });

  Object.defineProperties(obj, properties);

  return obj;
}

riot.observable = debuggableObserver;

```

End goal is to create a debugging tool to trace events with tree view to inspect passed arguments, etc. Similar to React's state debugger.
![screen shot 2017-08-30 at 6 03 58 pm](https://user-images.githubusercontent.com/4218587/29897179-b669c8b6-8dad-11e7-87a6-6eab69412cd7.png)

I'm eventually going to share the code once I get it working right, but I was wondering if it was a possibility to add hooks if not in this version, in Riot v4. That way I could make the debugger and not have to rewrap Observable.

**Comment by damusix** [comment]
For reference, here's my work to date:
- Wrapper: https://github.com/damusix/riot-utilities/blob/master/lib/observer.js
- Debugger: https://github.com/damusix/riot-utilities/tree/master/lib/debugger

**Comment by GianlucaGuarini** [comment]
thank you for your proposal but I don't want to pollute the core with new features I wouldn't personally use. A `debugger` statement in your callbacks should be enough for what you want to achieve.
Good luck
