### ISSUE TITLE
Add TypeScript types

### ISSUE THREAD

**Issue by chrismooredev** [riot/observable#33]
Could the project include types that allow the project to be safely used within TypeScript? Usually this can just be done with an extra types file that is referenced within the package.json. If there isn't any weirdness with how the package is distributed (I notice there's a regular script version and an es6 version, for example - I don't think that's expressible within TS) I'd be happy to take a shot and submit a PR.

If this package is already typed somewhere, please point me there and close this issue out :)

**Comment by GianlucaGuarini** [comment]
You could add the types with a PR. Basically you can reuse these https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/event-emitter/index.d.ts
