### ISSUE TITLE
try/catch shouldn't be used

### ISSUE THREAD

**Issue by pakastin** [riot/observable#8]
Events have a quite bad performance because of try/catch:
![profiling](https://cloud.githubusercontent.com/assets/1475902/10339718/7d4b0b9a-6d15-11e5-967a-ed82723241f2.png)
(_Bad value context for arguments value_ issue already fixed)

Try/catch should yet be removed:
https://github.com/riot/observable/blob/master/lib/index.js#L111-L116

Some info here:
https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#2-unsupported-syntax

**Comment by pakastin** [comment]
Related to #7.

**Comment by GianlucaGuarini** [comment]
This seems to be quite hard to fix..
According to this [test](https://jsperf.com/try-catch-performance-overhead/41) there is no big performance overhead

**Comment by pakastin** [comment]
That's because 1000 is the limit for a function being called concurrently – after that V8 optimizations cancel:
https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/compiler.cc&q=f:v8%20f:compiler%20kMaxOptCount&sq=package:chromium&type=cs&l=389

In that jsperf test there are exactly 1000 iterations, which is one over the limit :)

**Comment by pakastin** [comment]
I think jsperf also wraps everything to try/catch, which makes the test unvalid.

**Comment by pakastin** [comment]
..at least profiler gives warnings, even if I break before first test stops..

**Comment by pakastin** [comment]
I remember reading somewhere jsperf will break V8 optimizations. It shouldn't be trusted in these optimizations..

**Comment by pakastin** [comment]
Having any performance issue in events can be a true performance killer if you think about how many times events are triggered during Riot operations..

**Comment by GianlucaGuarini** [comment]
Ok so we should remove the `busy` flag then.. @tipiirai what do you think?

**Comment by pakastin** [comment]
I don't understand the logic there, but I may have a similar situation and this kind of fix:
https://github.com/pakastin/frzr/blob/master/lib/renderer.js#L18-L26

1) splice callbacks
2) loop them
3) if new callbacks added, start again from 1)

**Comment by pakastin** [comment]
Or actually in my Observable, I just do it like this:
https://github.com/pakastin/frzr/blob/master/lib/observable.js#L55-L62

..doesn't matter if listeners being added during the trigger loop.

**Comment by pakastin** [comment]
Here's how it's being done in Node.js:
https://github.com/nodejs/node/blob/master/lib/events.js

Notice that they have also taken care of the leaking arguments issue and no try/catch being used.

**Comment by GianlucaGuarini** [comment]
I think optimization is not necessary. I have included the `error` event to catch the internal errors. Thanks for you suggestion

**Comment by pakastin** [comment]
> I think optimization is not necessary.

That's crazy to say for eventEmitter.. Think about all the places they are used in and the actions their performance affects. But that's your call.

**Comment by GianlucaGuarini** [comment]
In the end I had to remove the `try/catch` block anyway because this way of hiding the javascript errors internally it was just a stupid idea :(

**Comment by pakastin** [comment]
:+1:
